#!/usr/bin/env python3
import cadquery as cq
from cadquery.vis import show

d = 30
dcut = 0.8
htext = 6


def make_text(s):
    def callback(wp):
        wp = wp.workplane(centerOption="CenterOfMass").text(
            s, htext, -dcut, font="RobotoMono Nerd Font"
        )
        return wp

    return callback


res = cq.Workplane().box(d, d, d)

res = res.faces(">Z").invoke(make_text("TOP"))
res = res.faces("<Z").invoke(make_text("BOTTOM"))
res = res.faces(">X").invoke(make_text("RIGHT"))
res = res.faces("<Y").invoke(make_text("FRONT"))
res = res.faces("<X").invoke(make_text("LEFT"))
res = res.faces(">Y").invoke(make_text("BACK"))

res.export("lorenz-wp.stl")

show(res)